DROP TABLE IF EXISTS APP_CONFIG_CHANGE;

CREATE TABLE APP_CONFIG_CHANGE ( 
   APPLICATION VARCHAR(50) NOT NULL, 
   STATUS VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS APP_CONFIG;

CREATE TABLE APP_CONFIG (
	KEY VARCHAR(50),
	VALUE VARCHAR(1024),
	APPLICATION VARCHAR(50),
	PROFILE VARCHAR(50),
	LABEL VARCHAR(50)
);

DROP TRIGGER IF EXISTS APP_CONFIG_INSERT_TRG;
DROP TRIGGER IF EXISTS APP_CONFIG_UPDATE_TRG;
DROP TRIGGER IF EXISTS APP_CONFIG_DELETE_TRG;

CREATE OR REPLACE FORCE TRIGGER  APP_CONFIG_INSERT_TRG AFTER INSERT ON APP_CONFIG FOR EACH ROW  CALL "com.springboot.configuration.utils.AppConfigTrigger";
CREATE OR REPLACE FORCE TRIGGER  APP_CONFIG_UPDATE_TRG AFTER UPDATE ON APP_CONFIG FOR EACH ROW  CALL "com.springboot.configuration.utils.AppConfigTrigger";
CREATE OR REPLACE FORCE TRIGGER  APP_CONFIG_DELETE_TRG AFTER DELETE ON APP_CONFIG FOR EACH ROW  CALL "com.springboot.configuration.utils.AppConfigTrigger";